apiVersion: apps/v1
kind: Deployment
metadata:
  name: plantuml-deployment
  labels:
    app: plantuml
spec:
  replicas: 1
  selector:
    matchLabels:
      app: plantuml
  template:
    metadata:
      labels:
        app: plantuml
    spec:
      containers:
      - name: plantuml
        image: plantuml/plantuml-server:tomcat
        ports:
        - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: plantuml-service
spec:
  selector:
    app: plantuml
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080

---
kind: Ingress
apiVersion: extensions/v1beta1
metadata:
  name: "plantuml"
  namespace: production

spec:
  rules:
    - host: martin-xps.local
      http:
        paths:
          - path: /uml
            backend:
              serviceName: plantuml-service
              servicePort: 80
