apiVersion: v1
kind: Namespace
metadata:
  name: plantuml

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: plantuml
  namespace: plantuml
  labels:
    app: plantuml
spec:
  replicas: 1
  selector:
    matchLabels:
      app: plantuml
  template:
    metadata:
      labels:
        app: plantuml
    spec:
      containers:
      - name: plantuml
        image: maddingo/plantuml-server
        ports:
        - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: plantuml
  namespace: plantuml
  #annotations:
    #service.beta.kubernetes.io/aws-load-balancer-ssl-cert: arn:aws:acm:eu-central-1:972842949248:certificate/b1f96b78-d292-4d9f-8c92-82854f418109
spec:
  selector:
    app: plantuml
  ports:
    - protocol: TCP
      port: 443
      targetPort: 8080
  type: LoadBalancer

---
kind: Ingress
apiVersion: extensions/v1beta1
metadata:
  name: "plantuml"
  namespace: plantuml

spec:
  rules:
    - host: plantuml.maddin.cloud
      http:
        paths:
          - path: /*
            backend:
              serviceName: plantuml
              servicePort: 443
